openapi: 3.0.0
info:
  title: Basic Auth test in Flask API
  version: 'Alpha'
servers:
  - url: /api
paths:
  /protected-basic:
    get:
      summary: Protected URL - need basic authorization
      operationId: app.get_basic_secret_info
      responses:
        '200':
          description: Return protected information in response
          content:
            '*/*':
              schema:
                type: string
      security:
        - basic: []
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: app.check_basic_auth
